name: Corbt
markdown: kramdown
highlighter: rouge
destination: /tmp/site
permalink: /posts/:categories/:year/:month/:day/:title.html

exclude: 
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

environments:
  prod:
    remote:
      connection: corbt
      path: /srv/www/corbt
